var settings,rightMnuId=null;function startOrRefresh(){loadSavedSettings();rightMnuOnOff()}startOrRefresh();chrome.runtime.onStartup.addListener(function(){loadSavedSettings();rightMnuOnOff()});
function loadSavedSettings(){settings={storedCanvas:{}};window.localStorage.buttonSettings||(window.localStorage.buttonSettings=JSON.stringify({addToMnu:!1,openInNewTab:!0}));settings=JSON.parse(window.localStorage.buttonSettings);icon=settings.redIcon?"red":settings.greenIcon?"green":settings.nudeIcon?"nude":settings.orangeIcon?"orange":settings.ownIcon?"own":"icon";updateIcon(icon)}
function updateIcon(b){if("own"==b){if(settings.ownIcon){var c=new Image;c.onload=function(){var a=document.createElement("canvas");a.width=c.width;a.height=c.height;a=a.getContext("2d");a.drawImage(c,0,0);a=a.getImageData(0,0,19,19);chrome.browserAction.setIcon({imageData:a})};c.setAttribute("src",settings.storedCanvas)}}else chrome.browserAction.setIcon({path:b+".png"})}
function versionCompare(b,c,a){function d(f){return(e?/^\d+[A-Za-z]*$/:/^\d+$/).test(f)}var e=a&&a.lexicographical;a=a&&a.zeroExtend;b=b.split(".");c=c.split(".");if(!b.every(d)||!c.every(d))return NaN;if(a){for(;b.length<c.length;)b.push("0");for(;c.length<b.length;)c.push("0")}e||(b=b.map(Number),c=c.map(Number));for(a=0;a<b.length;++a){if(c.length==a)return 1;if(b[a]!=c[a])return b[a]>c[a]?1:-1}return b.length!=c.length?-1:0}var currVersion=getVersion(),prevVersion=window.localStorage.button_Version;
function onInstall(){navigator.onLine&&chrome.tabs.create({url:"https://singleclickapps.com/plugins-button/postinstall-chrome.html"})}function onUpdate(){window.localStorage.versionUpdated=JSON.stringify({updated:!0})}function getVersion(){return chrome.runtime.getManifest().version}
chrome.runtime.onInstalled.addListener(function(b){currVersion!=prevVersion&&(window.localStorage.button_Version=currVersion);"install"==b.reason?"undefined"==typeof prevVersion&&onInstall():"update"==b.reason&&prevVersion!=currVersion&&onUpdate()});chrome.runtime.setUninstallURL("https://singleclickapps.com/plugins-button/removed-chrome.html");
function rightMnuOnOff(){settings.addToMnu&&null==rightMnuId&&(rightMnuId=chrome.contextMenus.create({title:"Plugins",type:"normal",contexts:"page frame selection link editable image video audio".split(" "),id:"menu1"}),chrome.contextMenus.create({title:"Global Content Settings",parentId:"menu1",contexts:"page frame selection link editable image video audio".split(" "),id:"globalMnuSet1"}),chrome.contextMenus.create({title:"Allow/Block on Current Site",parentId:"menu1",contexts:"page frame selection link editable image video audio".split(" "),
id:"currSiteAllBlock1"}),chrome.contextMenus.create({title:"Components List",parentId:"menu1",contexts:"page frame selection link editable image video audio".split(" "),id:"compMnuSet1"}),chrome.contextMenus.create({title:"Chrome Cleaner",parentId:"menu1",contexts:"page frame selection link editable image video audio".split(" "),id:"cleanerMnuSet1"}));settings.addToMnu||null==rightMnuId||(chrome.contextMenus.remove("compMnuSet1"),chrome.contextMenus.remove("currSiteAllBlock1"),chrome.contextMenus.remove("cleanerMnuSet1"),
chrome.contextMenus.remove("globalMnuSet1"),chrome.contextMenus.remove(rightMnuId),rightMnuId=null)}
chrome.contextMenus.onClicked.addListener(function(b,c){var a="";loadSavedSettings();if("globalMnuSet1"===b.menuItemId)a="chrome://settings/content";else if("compMnuSet1"===b.menuItemId)a="chrome://components";else if("cleanerMnuSet1"===b.menuItemId)a="chrome://settings/clearBrowserData";else if("currSiteAllBlock1"===b.menuItemId){siteSettings();return}settings.openInNewTab?chrome.tabs.create({url:a},function(d){window.close()}):chrome.tabs.query({currentWindow:!0,active:!0},function(d){chrome.tabs.update({url:a},
function(e){window.close()})})});function siteSettings(){var b=RegExp("^(?:f|ht)tp(?:s)?://([^/]+)","im"),c;chrome.tabs.getSelected(null,function(a){c=a.url;a=/^file:/.test(c)?c:c.match(b)[0]+"/*";if(null!==a){var d="chrome://settings/content/siteDetails?site="+encodeURIComponent(a);settings.openInNewTab?chrome.tabs.create({url:d},function(e){window.close()}):chrome.tabs.query({currentWindow:!0,active:!0},function(e){chrome.tabs.update({url:d},function(f){window.close()})})}})};